import { expect, test } from '@playwright/test'

test('native model selection, editable routes and destination mappings survive saving', async ({ page }) => {
  await page.goto('/demo')
  await page.getByRole('navigation').getByRole('button', { name: 'Clients', exact: true }).click()
  await page.getByRole('navigation').getByRole('button', { name: /Cursor/ }).click()
  await page.getByRole('tab', { name: 'LLM', exact: true }).click()
  await page.getByRole('combobox', { name: 'Choose a decision model', exact: true }).click()
  await expect(page.getByRole('option', { name: /openai/ })).toHaveCount(0)
  await page.getByRole('option', { name: 'ollaya-local / laya:en', exact: true }).click()
  await page.getByRole('combobox', { name: 'Routing template', exact: true }).click()
  await page.getByRole('option', { name: 'Custom question', exact: true }).click()
  await page.getByRole('textbox', { name: 'Routing question', exact: true }).fill('Does the user request a review?')
  await page.getByRole('textbox', { name: 'Route 1 ID', exact: true }).fill('review')
  await page.getByRole('textbox', { name: 'When to use review', exact: true }).fill('Review code without editing it.')
  await page.getByRole('combobox', { name: 'Add model to review', exact: true }).click()
  await expect(page.getByRole('option', { name: /laya/ })).toHaveCount(0)
  const destination = await page.getByRole('option').first().innerText()
  await page.getByRole('option').first().click()
  await page.getByRole('button', { name: 'Save routing policy', exact: true }).click()
  await expect(page.getByText('Routing policy saved', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Overview', exact: true }).click()
  await page.getByRole('tab', { name: 'LLM', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Choose a decision model', exact: true })).toContainText('laya:en')
  await expect(page.getByRole('textbox', { name: 'Routing question', exact: true })).toHaveValue('Does the user request a review?')
  await expect(page.getByRole('textbox', { name: 'Route 1 ID', exact: true })).toHaveValue('review')
  await expect(page.getByText(`1. ${destination}`, { exact: true })).toBeVisible()
})

test('exact mode preview overrides prompt text and missing mode uses the default', async ({ page }) => {
  await page.goto('/demo')
  await page.getByRole('navigation').getByRole('button', { name: 'Clients', exact: true }).click()
  await page.getByRole('navigation').getByRole('button', { name: /Cursor/ }).click()
  await page.getByRole('tab', { name: 'LLM', exact: true }).click()
  await page.getByRole('combobox', { name: 'Routing template', exact: true }).click()
  await page.getByRole('option', { name: 'Client mode: plan / otherwise', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Choose a decision model', exact: true })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Routing test prompt', exact: true }).fill('Implement the feature now.')
  await page.getByRole('textbox', { name: 'Test client mode', exact: true }).fill('plan')
  await page.getByRole('button', { name: 'Preview draft', exact: true }).click()
  await expect(page.getByText('client mode match', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Test client mode', exact: true }).fill('')
  await expect(page.getByText('client mode match', { exact: true })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Routing test prompt', exact: true }).fill('mode: plan. Please plan everything.')
  await page.getByRole('button', { name: 'Preview draft', exact: true }).click()
  await expect(page.getByText('demo simulation default', { exact: true })).toBeVisible()
})

test('original research renders evidence and bundled figures on desktop and mobile', async ({ page }) => {
  await page.goto('/research/decision-model-routing')
  await expect(page.getByRole('heading', { name: 'Decision Models for Configurable Routing', exact: true })).toBeVisible()
  await expect(page.getByRole('table')).toHaveCount(2)
  const figure = page.getByRole('img', { name: 'Historical correctness versus fraction routed to the strong model' })
  await expect(figure).toBeAttached()
  await expect.poll(() => figure.evaluate((el: HTMLImageElement) => el.naturalWidth)).toBeGreaterThan(0)
  await expect(page.getByRole('link', { name: 'research artifacts at commit 6cc5abd0' })).toHaveAttribute('href', /6cc5abd0/)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})
