import { useState } from "react"
import { Radio, CheckCircle2, XCircle, Clock, Bot, User, Settings } from "lucide-react"
import { Button } from "@/components/ui/Button"
import { Switch } from "@/components/ui/Toggle"
import { Label } from "@/components/ui/label"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/Badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card"
import { cn } from "@/lib/utils"
import type { CreateMessageResult } from "@/lib/mcp-client"
import type { PendingSamplingRequest } from "./index"

interface CompletedSamplingRequest {
  id: string
  params: PendingSamplingRequest["params"]
  timestamp: Date
  status: "completed" | "rejected"
  response?: CreateMessageResult
  error?: string
}

interface SamplingPanelProps {
  isConnected: boolean
  pendingRequests: PendingSamplingRequest[]
  onResolve: (id: string, result: CreateMessageResult) => void
  onReject: (id: string, error: string) => void
}

export function SamplingPanel({
  isConnected,
  pendingRequests,
  onResolve,
  onReject,
}: SamplingPanelProps) {
  const [completedRequests, setCompletedRequests] = useState<CompletedSamplingRequest[]>([])
  const [selectedRequestId, setSelectedRequestId] = useState<string | null>(null)
  const [autoApprove, setAutoApprove] = useState(false)

  // Find the selected request from either pending or completed
  const selectedPending = pendingRequests.find((r) => r.id === selectedRequestId)
  const selectedCompleted = completedRequests.find((r) => r.id === selectedRequestId)
  const selectedRequest = selectedPending || selectedCompleted

  // Auto-select first pending request if none selected
  if (!selectedRequest && pendingRequests.length > 0 && !selectedRequestId) {
    setSelectedRequestId(pendingRequests[0].id)
  }

  const handleApprove = async (request: PendingSamplingRequest) => {
    // For now, return a mock response - in a real implementation,
    // this would call an LLM to generate a response
    const mockResult: CreateMessageResult = {
      model: "mock-model",
      role: "assistant",
      content: {
        type: "text",
        text: "This is a mock response. In production, this would be generated by an LLM based on the sampling request.",
      },
      stopReason: "endTurn",
    }

    onResolve(request.id, mockResult)

    // Move to completed
    setCompletedRequests((prev) => [
      {
        id: request.id,
        params: request.params,
        timestamp: request.timestamp,
        status: "completed",
        response: mockResult,
      },
      ...prev,
    ])

    // Select next pending or clear selection
    const remainingPending = pendingRequests.filter((r) => r.id !== request.id)
    if (remainingPending.length > 0) {
      setSelectedRequestId(remainingPending[0].id)
    } else if (selectedRequestId === request.id) {
      setSelectedRequestId(null)
    }
  }

  const handleReject = async (request: PendingSamplingRequest) => {
    const errorMessage = "Request rejected by user"
    onReject(request.id, errorMessage)

    // Move to completed
    setCompletedRequests((prev) => [
      {
        id: request.id,
        params: request.params,
        timestamp: request.timestamp,
        status: "rejected",
        error: errorMessage,
      },
      ...prev,
    ])

    // Select next pending or clear selection
    const remainingPending = pendingRequests.filter((r) => r.id !== request.id)
    if (remainingPending.length > 0) {
      setSelectedRequestId(remainingPending[0].id)
    } else if (selectedRequestId === request.id) {
      setSelectedRequestId(null)
    }
  }

  const clearHistory = () => {
    setCompletedRequests([])
    if (pendingRequests.length > 0) {
      setSelectedRequestId(pendingRequests[0].id)
    } else {
      setSelectedRequestId(null)
    }
  }

  const getStatusBadge = (status: "pending" | "completed" | "rejected") => {
    switch (status) {
      case "pending":
        return (
          <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-200 dark:bg-yellow-950 dark:text-yellow-300 dark:border-yellow-800">
            <Clock className="h-3 w-3 mr-1" />
            Pending
          </Badge>
        )
      case "completed":
        return (
          <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200 dark:bg-green-950 dark:text-green-300 dark:border-green-800">
            <CheckCircle2 className="h-3 w-3 mr-1" />
            Completed
          </Badge>
        )
      case "rejected":
        return (
          <Badge variant="outline" className="bg-red-50 text-red-700 border-red-200 dark:bg-red-950 dark:text-red-300 dark:border-red-800">
            <XCircle className="h-3 w-3 mr-1" />
            Rejected
          </Badge>
        )
    }
  }

  // Combine pending and completed for display
  const allRequests = [
    ...pendingRequests.map((r) => ({ ...r, status: "pending" as const })),
    ...completedRequests,
  ].sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime())

  if (!isConnected) {
    return (
      <div className="flex items-center justify-center h-full text-muted-foreground">
        <p>Connect to an MCP server to monitor sampling requests</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full gap-4">
      {/* Controls */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="flex items-center space-x-2">
            <Switch
              id="auto-approve"
              checked={autoApprove}
              onCheckedChange={setAutoApprove}
            />
            <Label htmlFor="auto-approve">Auto-approve sampling requests</Label>
          </div>
        </div>
        <Button variant="outline" size="sm" onClick={clearHistory}>
          Clear History
        </Button>
      </div>

      <div className="flex h-full gap-4 min-h-0">
        {/* Left: Request List */}
        <div className="w-80 flex flex-col border rounded-lg">
          <div className="p-3 border-b flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Radio className="h-4 w-4" />
              <span className="font-medium text-sm">Sampling Requests</span>
            </div>
            <Badge variant="secondary">{allRequests.length}</Badge>
          </div>

          <ScrollArea className="flex-1">
            {allRequests.length === 0 ? (
              <div className="p-4 text-sm text-muted-foreground text-center">
                <p>No sampling requests yet</p>
                <p className="text-xs mt-1">
                  Requests from MCP servers will appear here
                </p>
              </div>
            ) : (
              <div className="p-2 space-y-1">
                {allRequests.map((request) => (
                  <button
                    key={request.id}
                    onClick={() => setSelectedRequestId(request.id)}
                    className={cn(
                      "w-full text-left p-2 rounded-md transition-colors",
                      "hover:bg-accent",
                      selectedRequestId === request.id && "bg-accent"
                    )}
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-medium truncate">
                        Sampling Request
                      </span>
                      {getStatusBadge(request.status)}
                    </div>
                    <p className="text-xs text-muted-foreground mt-1">
                      {request.timestamp.toLocaleTimeString()}
                    </p>
                    {request.params.modelPreferences?.hints?.[0]?.name && (
                      <p className="text-xs text-muted-foreground truncate">
                        Model hint: {request.params.modelPreferences.hints[0].name}
                      </p>
                    )}
                  </button>
                ))}
              </div>
            )}
          </ScrollArea>
        </div>

        {/* Right: Request Details */}
        <div className="flex-1 flex flex-col border rounded-lg">
          {selectedRequest ? (
            <>
              <div className="p-4 border-b">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="font-semibold">Sampling Request</h3>
                    <p className="text-xs text-muted-foreground">
                      {selectedRequest.timestamp.toLocaleString()}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    {getStatusBadge(selectedPending ? "pending" : selectedCompleted?.status || "pending")}
                    {selectedPending && (
                      <>
                        <Button
                          size="sm"
                          onClick={() => handleApprove(selectedPending)}
                        >
                          <CheckCircle2 className="h-4 w-4 mr-1" />
                          Approve
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleReject(selectedPending)}
                        >
                          <XCircle className="h-4 w-4 mr-1" />
                          Reject
                        </Button>
                      </>
                    )}
                  </div>
                </div>
              </div>

              <ScrollArea className="flex-1 p-4">
                <div className="space-y-6">
                  {/* Request Messages */}
                  <div className="space-y-2">
                    <h4 className="text-sm font-medium">Request Messages</h4>
                    <div className="space-y-3">
                      {selectedRequest.params.messages.map((msg, idx) => (
                        <div
                          key={idx}
                          className={cn(
                            "flex gap-3",
                            msg.role === "user" ? "justify-end" : "justify-start"
                          )}
                        >
                          {msg.role === "assistant" && (
                            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-muted">
                              <Bot className="h-4 w-4" />
                            </div>
                          )}
                          <div
                            className={cn(
                              "rounded-lg px-4 py-2 max-w-[80%]",
                              msg.role === "user"
                                ? "bg-primary text-primary-foreground"
                                : "bg-muted"
                            )}
                          >
                            <p className="text-sm whitespace-pre-wrap">
                              {typeof msg.content === "string"
                                ? msg.content
                                : "text" in msg.content
                                  ? msg.content.text
                                  : JSON.stringify(msg.content)}
                            </p>
                          </div>
                          {msg.role === "user" && (
                            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary">
                              <User className="h-4 w-4 text-primary-foreground" />
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Model Preferences */}
                  {selectedRequest.params.modelPreferences && (
                    <Card>
                      <CardHeader className="py-2">
                        <CardTitle className="text-sm flex items-center gap-2">
                          <Settings className="h-4 w-4" />
                          Model Preferences
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="py-2 space-y-2">
                        {selectedRequest.params.modelPreferences.hints &&
                          selectedRequest.params.modelPreferences.hints.length > 0 && (
                            <div className="flex items-center gap-2">
                              <span className="text-xs text-muted-foreground">Hints:</span>
                              {selectedRequest.params.modelPreferences.hints.map((hint, idx) => (
                                <Badge key={idx} variant="secondary" className="text-xs">
                                  {hint.name}
                                </Badge>
                              ))}
                            </div>
                          )}
                        <div className="flex gap-4 text-xs">
                          {selectedRequest.params.modelPreferences.costPriority !== undefined && (
                            <span>Cost: {selectedRequest.params.modelPreferences.costPriority}</span>
                          )}
                          {selectedRequest.params.modelPreferences.speedPriority !== undefined && (
                            <span>Speed: {selectedRequest.params.modelPreferences.speedPriority}</span>
                          )}
                          {selectedRequest.params.modelPreferences.intelligencePriority !== undefined && (
                            <span>
                              Intelligence: {selectedRequest.params.modelPreferences.intelligencePriority}
                            </span>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  )}

                  {/* Parameters */}
                  <div className="flex gap-4">
                    {selectedRequest.params.temperature !== undefined && (
                      <Badge variant="outline">Temperature: {selectedRequest.params.temperature}</Badge>
                    )}
                    {selectedRequest.params.maxTokens !== undefined && (
                      <Badge variant="outline">Max Tokens: {selectedRequest.params.maxTokens}</Badge>
                    )}
                  </div>

                  {/* System Prompt */}
                  {selectedRequest.params.systemPrompt && (
                    <div className="space-y-2">
                      <h4 className="text-sm font-medium">System Prompt</h4>
                      <pre className="p-3 bg-muted rounded-md text-xs whitespace-pre-wrap">
                        {selectedRequest.params.systemPrompt}
                      </pre>
                    </div>
                  )}

                  {/* Response (for completed requests) */}
                  {selectedCompleted?.response && (
                    <div className="space-y-2">
                      <h4 className="text-sm font-medium flex items-center gap-2">
                        Response
                        <Badge variant="secondary" className="text-xs">
                          {selectedCompleted.response.model}
                        </Badge>
                      </h4>
                      <div className="flex gap-3">
                        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-muted">
                          <Bot className="h-4 w-4" />
                        </div>
                        <div className="rounded-lg px-4 py-2 bg-muted max-w-[80%]">
                          <p className="text-sm whitespace-pre-wrap">
                            {typeof selectedCompleted.response.content === "string"
                              ? selectedCompleted.response.content
                              : "text" in selectedCompleted.response.content
                                ? selectedCompleted.response.content.text
                                : JSON.stringify(selectedCompleted.response.content)}
                          </p>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Error */}
                  {selectedCompleted?.error && (
                    <div className="p-3 bg-destructive/10 text-destructive rounded-md text-sm">
                      {selectedCompleted.error}
                    </div>
                  )}
                </div>
              </ScrollArea>
            </>
          ) : (
            <div className="flex items-center justify-center h-full text-muted-foreground">
              <p>Select a request to view details</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
