//! OpenCode integration
//!
//! Config-file only (no try-it-out). Modifies `<config_dir>/opencode/opencode.json`
//! to add LocalRouter as an LLM provider and MCP server.
//!
//! MCP format: key `"mcp"` (not `"mcpServers"`), type `"remote"` (not `"http"`).

use crate::launcher::backup;
use crate::launcher::{AppIntegration, ConfigSyncContext};
use crate::ui::commands_clients::{AppCapabilities, LaunchResult};
use std::path::PathBuf;

pub struct OpenCodeIntegration;

fn config_path() -> PathBuf {
    // OpenCode uses XDG config path (~/.config/opencode/) on all platforms,
    // not the macOS-native ~/Library/Application Support/
    xdg_config_dir().join("opencode").join("opencode.json")
}

fn xdg_config_dir() -> PathBuf {
    std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| dirs::home_dir().unwrap_or_default().join(".config"))
}

/// Extra root CA env var. Bun honors Node's `NODE_EXTRA_CA_CERTS` additively,
/// and opencode's own network docs name it. (The shipped binary is also built
/// with `--use-system-ca`, so a CA trusted in the OS store works with no env
/// var at all — this is the belt-and-suspenders path.)
pub const PROXY_CA_ENV_VAR: &str = "NODE_EXTRA_CA_CERTS";

/// Loopback hosts that must bypass the proxy. opencode's TUI talks to its own
/// local HTTP server; routing that through the proxy creates a request loop.
/// opencode's network documentation calls this out explicitly.
pub const PROXY_NO_PROXY: &str = "localhost,127.0.0.1,::1";

/// Path of the plugin file that applies the proxy settings permanently.
///
/// opencode has no `env` block in `opencode.json` and its compiled binary is
/// built with `autoloadDotenv: false`, so there is no dotenv hook. What it
/// does have is a global plugin directory that is auto-loaded on every start
/// (`~/.config/opencode/plugin/*.ts`), and Bun reads proxy env vars per
/// request — so a tiny plugin that sets `process.env` at import time
/// configures the proxy for every opencode invocation.
pub fn plugin_file_path() -> PathBuf {
    xdg_config_dir()
        .join("opencode")
        .join("plugin")
        .join("localrouter-proxy.ts")
}

/// One-off terminal command to launch opencode through the inspection proxy.
pub fn proxy_oneoff_command(proxy_url: &str, ca_cert_path: &str) -> String {
    format!(
        "HTTPS_PROXY={proxy_url} NO_PROXY={PROXY_NO_PROXY} {PROXY_CA_ENV_VAR}={ca_cert_path} opencode"
    )
}

/// Body of the auto-loaded plugin. This file is entirely LocalRouter-owned and
/// regenerated on every configure, so it is safe to overwrite wholesale —
/// unlike the user's `opencode.json`, which we never touch for proxy setup.
pub fn proxy_plugin_source(proxy_url: &str, ca_cert_path: &str) -> String {
    // JSON-encode the interpolated values so quotes/backslashes in a path or
    // a percent-encoded credential can't break out of the string literal.
    let url = serde_json::to_string(proxy_url).unwrap_or_else(|_| "\"\"".to_string());
    let ca = serde_json::to_string(ca_cert_path).unwrap_or_else(|_| "\"\"".to_string());
    let no_proxy = serde_json::to_string(PROXY_NO_PROXY).unwrap_or_else(|_| "\"\"".to_string());
    format!(
        r#"// Generated by LocalRouter — HTTPS inspection proxy configuration.
// Delete this file (or turn off proxy mode for this client) to stop routing
// opencode's LLM traffic through LocalRouter.
//
// opencode has no env block in opencode.json and the compiled binary disables
// dotenv autoloading, so this auto-loaded plugin is the supported way to set
// process-wide env vars. Bun reads proxy env vars per request, and opencode's
// own websocket transport resolves the proxy at connect time, so setting them
// here takes effect for both the HTTP and wss Codex transports.

process.env.HTTPS_PROXY = {url};
process.env.https_proxy = {url};
// Loopback must bypass the proxy: the TUI talks to opencode's local server.
process.env.NO_PROXY = {no_proxy};
process.env.no_proxy = {no_proxy};
process.env.{ca_var} = {ca};

export default async () => ({{}});
"#,
        url = url,
        ca = ca,
        no_proxy = no_proxy,
        ca_var = PROXY_CA_ENV_VAR,
    )
}

/// Read the existing opencode.json or create an empty object
fn read_config(path: &std::path::Path) -> serde_json::Value {
    if path.exists() {
        let data = std::fs::read_to_string(path).unwrap_or_default();
        serde_json::from_str(&data).unwrap_or(serde_json::json!({}))
    } else {
        serde_json::json!({})
    }
}

/// Build the MCP server entry (shared between configure_permanent and sync_config)
fn mcp_entry(base_url: &str, client_secret: &str) -> serde_json::Value {
    serde_json::json!({
        "type": "remote",
        "url": base_url,
        "headers": {
            "Authorization": format!("Bearer {}", client_secret)
        }
    })
}

/// Write config JSON to disk with backup
fn write_config(
    path: &std::path::Path,
    config: &serde_json::Value,
) -> Result<LaunchResult, String> {
    let data = serde_json::to_string_pretty(config)
        .map_err(|e| format!("Failed to serialize config: {}", e))?;

    let backup_path = backup::write_with_backup(path, data.as_bytes())?;
    let backup_files: Vec<String> = backup_path
        .iter()
        .map(|p| p.to_string_lossy().to_string())
        .collect();

    Ok(LaunchResult {
        success: true,
        message: format!(
            "Configured OpenCode at {}. Run /connect in OpenCode to apply changes.",
            path.display()
        ),
        modified_files: vec![path.to_string_lossy().to_string()],
        backup_files,
        terminal_command: None,
    })
}

impl AppIntegration for OpenCodeIntegration {
    fn name(&self) -> &str {
        "OpenCode"
    }

    fn check_installed(&self) -> AppCapabilities {
        let binary = super::find_binary("opencode");

        AppCapabilities {
            installed: binary.is_some(),
            binary_path: binary.map(|p| p.to_string_lossy().to_string()),
            version: None,
            supports_try_it_out: self.supports_try_it_out(),
            supports_permanent_config: self.supports_permanent_config(),
        }
    }

    fn supports_permanent_config(&self) -> bool {
        true
    }

    fn needs_model_list(&self) -> bool {
        true
    }

    fn configure_permanent(
        &self,
        base_url: &str,
        client_secret: &str,
        _client_id: &str,
    ) -> Result<LaunchResult, String> {
        self.write_config(base_url, client_secret, true, true, None)
    }

    fn sync_config(&self, ctx: &ConfigSyncContext) -> Result<LaunchResult, String> {
        self.write_config(
            &ctx.base_url,
            &ctx.client_secret,
            ctx.should_sync_llm(),
            ctx.should_sync_mcp(),
            Some(&ctx.models),
        )
    }
}

impl OpenCodeIntegration {
    fn write_config(
        &self,
        base_url: &str,
        client_secret: &str,
        sync_llm: bool,
        sync_mcp: bool,
        models: Option<&Vec<String>>,
    ) -> Result<LaunchResult, String> {
        let path = config_path();

        // Nothing to write or clean up
        if !sync_llm && !sync_mcp && !path.exists() {
            return Ok(LaunchResult {
                success: true,
                message: "No config to sync for current client mode".to_string(),
                modified_files: vec![],
                backup_files: vec![],
                terminal_command: None,
            });
        }

        let mut config = read_config(&path);

        if let Some(obj) = config.as_object_mut() {
            // LLM provider entry
            if sync_llm {
                let mut provider_entry = serde_json::json!({
                    "npm": "@ai-sdk/openai-compatible",
                    "name": "LocalRouter",
                    "options": {
                        "baseURL": format!("{}/v1", base_url),
                        "apiKey": client_secret
                    }
                });

                // Add models map if provided (from sync_config)
                if let Some(model_list) = models {
                    let mut models_map = serde_json::Map::new();
                    for model_id in model_list {
                        models_map
                            .insert(model_id.clone(), serde_json::json!({ "name": model_id }));
                    }
                    provider_entry["models"] = serde_json::Value::Object(models_map);
                }

                let provider = obj
                    .entry("provider")
                    .or_insert_with(|| serde_json::json!({}));
                if let Some(prov_obj) = provider.as_object_mut() {
                    prov_obj.insert("localrouter".to_string(), provider_entry);
                }
            } else {
                // Remove stale LLM entry
                if let Some(provider) = obj.get_mut("provider") {
                    if let Some(prov_obj) = provider.as_object_mut() {
                        prov_obj.remove("localrouter");
                    }
                }
            }

            // OpenCode uses "mcp" key (not "mcpServers")
            if sync_mcp {
                let mcp = obj.entry("mcp").or_insert_with(|| serde_json::json!({}));
                if let Some(mcp_obj) = mcp.as_object_mut() {
                    mcp_obj.insert(
                        "localrouter".to_string(),
                        mcp_entry(base_url, client_secret),
                    );
                }
            } else {
                // Remove stale MCP entry
                if let Some(mcp) = obj.get_mut("mcp") {
                    if let Some(mcp_obj) = mcp.as_object_mut() {
                        mcp_obj.remove("localrouter");
                    }
                }
            }
        }

        write_config(&path, &config)
    }
}

#[cfg(test)]
mod proxy_tests {
    use super::*;

    #[test]
    fn oneoff_command_includes_loopback_no_proxy() {
        let cmd = proxy_oneoff_command("http://p", "/ca.pem");
        // Without NO_PROXY the TUI's calls to its own local server loop back
        // through the proxy.
        assert!(cmd.contains("NO_PROXY=localhost,127.0.0.1,::1"));
        assert!(cmd.contains("HTTPS_PROXY=http://p"));
        assert!(cmd.contains("NODE_EXTRA_CA_CERTS=/ca.pem"));
        assert!(cmd.ends_with(" opencode"));
    }

    #[test]
    fn plugin_sets_proxy_ca_and_no_proxy() {
        let src = proxy_plugin_source("http://user:sec@127.0.0.1:3626", "/ca.pem");
        assert!(src.contains(r#"process.env.HTTPS_PROXY = "http://user:sec@127.0.0.1:3626""#));
        assert!(src.contains(r#"process.env.NODE_EXTRA_CA_CERTS = "/ca.pem""#));
        assert!(src.contains(r#"process.env.NO_PROXY = "localhost,127.0.0.1,::1""#));
        // Lowercase aliases too — some stacks only read those.
        assert!(src.contains("process.env.https_proxy"));
        assert!(src.contains("process.env.no_proxy"));
        // Must be a valid plugin module.
        assert!(src.contains("export default"));
    }

    #[test]
    fn plugin_escapes_values_so_they_cannot_break_the_string_literal() {
        // A quote or backslash in the secret/path must not terminate the JS
        // string (which would be a code-injection vector into the plugin).
        let src = proxy_plugin_source("http://u:a\"b\\c@h:1", "/pa\"th.pem");
        assert!(src.contains(r#""http://u:a\"b\\c@h:1""#));
        assert!(src.contains(r#""/pa\"th.pem""#));
        // No raw unescaped quote sequence that would end the literal early.
        assert!(!src.contains("= \"http://u:a\"b"));
    }

    #[test]
    fn plugin_path_is_in_the_autoloaded_global_plugin_dir() {
        let p = plugin_file_path();
        assert!(p.ends_with("opencode/plugin/localrouter-proxy.ts"));
    }
}
